---
title: "Figure S6"
output: html_notebook
---

# Libraries
```{r message=FALSE, warning=FALSE, echo=FALSE,include=FALSE}
rm(list = ls())

library(lmerTest)
library(lme4)
library(emmeans)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(rstatix)
library(effsize)
library(magrittr)
library(knitr)
library(xtable)
library(kableExtra)
library(openxlsx)


```

# Helping functions
```{r}


tab_anova <- function(model, digits = 1, eps = .001) {
  sjPlot::tab_df(broom::tidy(anova(model)) %>%
                   mutate(p.value = format.pval(
                     p.value, digits = digits, eps = eps
                   )),
                 digits = digits)
}

adj <- function(df, x, y, val, paired = F) {
  stat.test <- df %>%
    rstatix::t_test(as.formula(paste0(val, '~', x)),
                    paired = paired) %>%
    add_xy_position(x = x) %>%
    adjust_pvalue(method = "bonferroni") %>%
    add_significance("p.adj")
  
  return(stat.test)
}


adj2 <- function(df, x, y, val, paired = F) {
  stat.test <- df %>%
    group_by_at(y) %>%
    rstatix::t_test(as.formula(paste0(val, '~', x)),
                    paired = paired) %>%
    add_xy_position(x = x, dodge = 0.8) %>%
    adjust_pvalue(method = "bonferroni") %>%
    add_significance("p.adj")
  
  return(stat.test)
}

to_sign  <- function(df, col = "P-Value") {
  df %>% mutate(
    `P-Sign` = case_when(
      !!as.name(col) > 0.05 ~ "n.s.",!!as.name(col)  <= 0.05 &
        !!as.name(col)   > 0.01 ~ "*",!!as.name(col)  <= 0.01 &
        !!as.name(col)   > 0.001 ~ "**",!!as.name(col)   <= 0.001 &
        !!as.name(col)   > 0.0001 ~ "***",!!as.name(col)   <= 0.0001 ~ "****"
    )
  )
  
}


```

# Data
```{r}

df.EGG        <- readRDS("../Data/EGG.RDS")
demographics  <- read.csv("../Data/Demographics.csv")
```

# Figures 
```{r message=FALSE, warning=FALSE}
my_comparisons <- list(c("Baseline", "Normal"),
                       c("Normal", "Enhanced"),
                       c("Baseline", "Enhanced"))

metrics <- c("Normogasteria",
             "Tachygastria",
             "Bradygastria")

p.list <- list()
df.all.stat <- NULL
df.all.stat.pariwise <- NULL
for (m in metrics) {
  tmp <- df.EGG[[m]] %>%
    select(c(m, "id", "Block")) %>%
    merge(demographics, by = "id") %>%
    filter(Source == "Original")
  tmp$Block     <-
    factor(tmp$Block, levels = c('Baseline', 'Normal', 'Enhanced'))
  
  fit        <-
    lmer(as.formula(paste0(m, '~', 'Block',  '+', '(1|id)')),
         data = tmp)
  tmp.rs     <-
    anova(fit) %>% as.data.frame() %>% `rownames<-`(NULL) %>%
    mutate(Analysis = m)
  
  df.all.stat <- rbind(df.all.stat, tmp.rs)
  
  #cat(paste0("#################################### ","\n"))
  
  tmp.pairwise <- emmeans(fit, list(pairwise  ~ Block),
                          adjust = "bonferroni")  #post hoc (two correction egs)
  tmp.pairwise <-
    as.data.frame(tmp.pairwise$`pairwise differences of Block`) %>%
    `colnames<-`(c("Comparison", "Estimate", "SE", "DF", "t-stat", "P-Value")) %>%
    mutate(Analysis = m) %>%
    select(-c(SE))
  # Confidence intervals
  
  tmp.pairwise <- tmp.pairwise %>% merge(as.data.frame(eff_size(
    emmeans(fit, "Block"),
    sigma = sigma(fit),
    edf = df.residual(fit)
  )) %>%
    select(c(
      'effect.size', 'SE', 'contrast', 'lower.CL', 'upper.CL'
    )) %>%
    rename("Comparison" = "contrast"))
  
  df.all.stat.pariwise <- rbind(df.all.stat.pariwise, tmp.pairwise)
  df.all.stat <- rbind(df.all.stat, tmp.rs)
  
  q <- ggboxplot(
    tmp,
    x = "Block",
    y = m,
    combine = T,
    fill = "Block",
    palette = c("#7E6148B2",
                           "#3C5488B2",
                           "#00A087B2"),
                           ylab = 'Power',
    xlab = 'Block',
    ncol = 1,
    title = paste(m),
    facet.by = "Source"
  ) +
    theme_pubclean() +
    theme(
      axis.text.x  = element_text(size = 13),
      axis.text.y  = element_text(size = 13),
      legend.position = 'top',
      axis.title  = element_text(size = 13)
    )
  p.list[[m]] <- q
  
  
  rm(fit, tmp, q, tmp.rs, tmp.pairwise)
}


```

```{r}
p  <-cowplot::plot_grid(plotlist = p.list)
p
#ggsave('../Figures/FigureS6.svg', dpi = 600)
```

# Stats
```{r}
df.all.stat<- df.all.stat%>%
  mutate_at(c("Sum Sq", "Mean Sq", "DenDF"), format, digits = 3)%>%
  mutate_at(c( "F value"), round, 3)%>%
  mutate_at(c( "Pr(>F)"), round, 5)%>%
  relocate("Analysis","Pr(>F)", "F value")%>%
  rename("P-Value"="Pr(>F)")
  df.all.stat%>%
  kbl(caption = "Summary") %>%
  kable_paper("hover", full_width = F, position = "left")
  
#
file = '../Excel/Data_sharing_Summary.xlsx'
# Aappend To existing sheet 
wb <- loadWorkbook(file)
addWorksheet(wb, "FigureS6-LME")
writeData(wb,
          "FigureS6-LME",
          df.all.stat,
          colNames = TRUE,
          rowNames = FALSE)

saveWorkbook(wb, file, overwrite = TRUE)


df.all.stat.pariwise<-df.all.stat.pariwise%>%to_sign()%>%
  mutate_at(c( "Estimate", "SE","t-stat", "upper.CL", "lower.CL","effect.size"), round, 3)%>%
  mutate_at(c("SE"), round, 3)%>%
  mutate_at(c( "DF"), round, 1)%>%
  mutate_at(c( "P-Value", "SE"), round, 5)%>%
  mutate("95% CI"=paste0("[", lower.CL, ", ", upper.CL,"]"))%>%
  select(-c(lower.CL, upper.CL))%>%
  rename("Cohen’s d"="effect.size")%>%
  relocate("Analysis", "Comparison","P-Sign","P-Value",	"Cohen’s d", 	
           "95% CI","t-stat" )

wb <- loadWorkbook(file)
addWorksheet(wb, "FigureS6-Posthoc")
writeData(wb,
          "FigureS6-Posthoc",
          df.all.stat.pariwise,
          colNames = TRUE,
          rowNames = FALSE)

saveWorkbook(wb, file, overwrite = TRUE)

df.all.stat.pariwise%>%
  kbl(caption = "post-hoc") %>%
  kable_paper("hover", full_width = F, position = "left")


rm(df.all.stat.pariwise,df.all.stat)
```

# Write Data to Excel
```{r}
# Convert list to data frame
df.EGG_all<-NULL
for (m in names(df.EGG)){
  tmp            <- df.EGG[[m]]
  names(tmp)     <- c('Value', 'id', 'Block')
  tmp['Measure'] <- m
  df.EGG_all     <- rbind(df.EGG_all, tmp)
  rm(tmp)
}

rm(df.EGG)
df_ready<-df.EGG_all %>%
  merge(demographics, by='id')%>%
  rename("Sample" = "Source") %>%
  filter(Sample=='Original')%>%
  select(c("id", "Measure", "Block", "Value"))%>%
  filter(Measure %in% metrics)

#
file = '../Excel/Data_sharing_Raw.xlsx'
# Aappend To existing sheet 
wb <- loadWorkbook(file)
addWorksheet(wb, "FigureS6")
writeData(wb,
          "FigureS6",
          df_ready,
          colNames = TRUE,
          rowNames = FALSE)

saveWorkbook(wb, file, overwrite = TRUE)

```
# Number of Samples
```{r}
df_ready %>%
  group_by(Measure, Block)%>%
  count()
```

