---
title: "Figure 5 Stats"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, echo=FALSE,include=FALSE}
rm(list = ls())
library(lme4)
library(lmerTest)
library(emmeans)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(rstatix)
library(effsize)
library(magrittr)
library(knitr)
library(xtable)
library(kableExtra)
library("openxlsx")

```

# Helping Functions
```{r}
to_sign  <- function(df, col = "P-Value") {
  df %>% mutate(
    `P-Sign` = case_when(
      !!as.name(col) > 0.05 ~ "n.s.",!!as.name(col)  <= 0.05 &
        !!as.name(col)   > 0.01 ~ "*",!!as.name(col)  <= 0.01 &
        !!as.name(col)   > 0.001 ~ "**",!!as.name(col)   <= 0.001 &
        !!as.name(col)   > 0.0001 ~ "***",!!as.name(col)   <= 0.0001 ~ "****"
    )
  )
  
}

```

# Read Data
```{r}
file <- '../Excel/Data_sharing_Raw.xlsx'
```

# Figure2 Stats
```{r message=FALSE, warning=FALSE, echo=FALSE,include=FALSE}
df        <- read.xlsx(file, 'Figure4')
Measures   <- unique(df$Measure)
df.all.stat   <- NULL
df.all.stat.pariwise <- NULL

for (f in Measures) {
  
  # 
  tmp <- df %>%
    filter(Measure==f)
  # Models
  fit       <-   lmerTest::lmer(Value ~ Block + (1 | id), data = tmp)
  # put results in data framer
  tmp.rs     <- anova(fit) %>%
    as.data.frame() %>%
    `rownames<-`(NULL) %>%
    mutate(Analysis = f)
  
  # Append to all data results data frame
  df.all.stat <- rbind(df.all.stat, tmp.rs)
  
  # Post-hoc
  tmp.pairwise <- emmeans(fit, list(pairwise  ~ Block),
                          adjust = "bonferroni")  
  tmp.pairwise <-
    as.data.frame(tmp.pairwise$`pairwise differences of Block`) %>%
    `colnames<-`(c("Comparison", "Estimate", "SE", "DF", "t-stat", "P-Value")) %>%
    mutate(Analysis = f) %>%
    select(-c(SE))
  
  # Confidence intervals
  tmp.pairwise <- tmp.pairwise %>% 
    merge(as.data.frame(eff_size(
    emmeans(fit, "Block"),
    sigma = sigma(fit),
    edf = df.residual(fit)
  )) %>%
    select(c(
      'effect.size', 'SE', 'contrast', 'lower.CL', 'upper.CL'
    )) %>%
    rename("Comparison" = "contrast"))
  
  # append results
  df.all.stat.pariwise <-
    rbind(df.all.stat.pariwise, tmp.pairwise)
  
  rm(tmp, tmp.rs, fit, tmp.pairwise)
}
rm(df)

```

# Print Results
## F-stat
```{r}
file = '../Excel/Data_sharing_Summary.xlsx'

```

```{r}

df.all.stat <- df.all.stat %>%
  #rename(c("P-Value"="Pr(>F)"))%>%
  mutate_at(c("Sum Sq", "Mean Sq", "DenDF"), format, digits = 3)%>%
  mutate_at(c( "F value"), round, 3)%>%
  mutate_at(c( "P-Value"), round, 5)%>%
  relocate("Analysis","P-Value", "F value")

  df.all.stat%>%
    kbl(caption = "Summary") %>%
  kable_paper("basic", full_width = F, position = "left")



write.xlsx(
  df.all.stat,
  file,
  sheetName = "Figure4-LME",
  colNames = TRUE,
  #row.names = TRUE,
  append = TRUE
)
```

## Post-Hoc
```{r}
df.all.stat.pariwise <- df.all.stat.pariwise %>%
  to_sign() %>%
  mutate_at(c(
    "Estimate",
    "SE",
    "t-stat",
    "upper.CL",
    "lower.CL",
    "effect.size"
  ),
  round,
  3) %>%
  mutate_at(c("SE"), round, 3) %>%
  mutate_at(c("DF"), round, 1) %>%
  mutate_at(c("P-Value"),
            format.pval,
            digits = 5,
            nsmall = 5) %>%
  mutate("95% CI" = paste0("[", lower.CL, ", ", upper.CL, "]")) %>%
  select(-c(lower.CL, upper.CL)) %>%
  rename("Cohen’s d" = "effect.size") %>%
  relocate("Analysis",
           "Comparison",
           "P-Sign",
           "P-Value",
           "Cohen’s d",
           "95% CI",
           "t-stat")
df.all.stat.pariwise %>%
  kbl(caption = "post-hoc") %>%
  kable_paper("basic", full_width = F, position = "left")

# Aappend To existing sheet 
wb <- loadWorkbook(file)
addWorksheet(wb, "Figure4-Posthoc")
writeData(wb,
          "Figure4-Posthoc",
          df.all.stat.pariwise,
          col.names = TRUE,
          row.names = FALSE)

saveWorkbook(wb, file, overwrite = TRUE)

```
```


